### ISSUE TITLE
Terminal highlight background and foreground colors clash

### ISSUE THREAD

**Issue by mindflux** [Michaelzhouisnotwhite/Jetbrains-Fleet-Theme#12]
Highlighting text in terminal makes the selected text background gray-ish and the text the same color, so you cannot tell what you're highlighting.

![2022-11-01 09_18_31-settings json - powershell (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/1136358/199255255-67b54f8a-b31d-44a9-8a02-322fe2c799e2.png)
![2022-11-01 09_18_39-settings json - powershell (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/1136358/199255257-f6987aca-4a1c-4f4c-bccd-2fef5a4abb0d.png)

**Comment by mindflux** [comment]
changing:
    "terminal.selectionBackground": "#636262fd",
to:
    "terminal.selectionBackground": "#636262",

is enough of a fix
![2022-11-01 09_37_33-BackupData ps1 - powershell (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/1136358/199259543-24ac25e0-89be-4a26-a9cb-1ee247129226.png)

**Comment by Michaelzhouisnotwhite** [comment]
Thanks your feedback. I'll fix it in the next version.
