### ISSUE TITLE
Would you be able to publish the theme on open-vsx?

### ISSUE THREAD

**Issue by one-juru** [Michaelzhouisnotwhite/Jetbrains-Fleet-Theme#18]
Hey, first of all, thank you for your awesome theme! 

Sadly, my company decided to move away from letting developers choose their environments and are instead transitioning to managed vscode-servers, and removing the rights from us developers to install anything on our machines.

Since the new environment uses a fork of VS Code which is specifically modified for servers but isn't published by Microsoft, they're not using the official extension gallery and instead rely on Open-VSX (https://open-vsx.org). Open-VSX hosts extensions for VS Code Compatible Editors (like VS Code Server). 

Quoting from this issue: https://github.com/microsoft/vscode/issues/31168

> Microsoft does state that only their "Visual Studio" products are allowed to use their extension gallery in their [Terms of Use](https://aka.ms/vsmarketplace-ToU), under section 1b, Visual Studio Products and Services:

>> Marketplace Offerings are intended for use only with Visual Studio Products and Services and you may only install and use Marketplace Offerings with Visual Studio Products and Services.

Do you think you're able to publish your awesome theme to Open-VSX aswell, so I can continue to use it? :)

**Comment by Michaelzhouisnotwhite** [comment]
done. <https://open-vsx.org/extension/MichaelZhou/fleet-theme>
