### ISSUE TITLE
How to change brackets color?

### ISSUE THREAD

**Issue by petrisoralexandru** [Michaelzhouisnotwhite/Jetbrains-Fleet-Theme#2]
Hello, what are the color hex codes and what properties should watch? I would  like to change this blue and orange.

![image](https://user-images.githubusercontent.com/34144926/182003062-6ed2a097-14dd-4898-b851-f18a208e52fc.png)

**Comment by Michaelzhouisnotwhite** [comment]
I don't understand what you mean. One token and scope can only correspond to one color.
