### ISSUE TITLE
希望能出个jetbrains新ui一样的vscode主题

### ISSUE THREAD

**Issue by EdwardChen1993** [Michaelzhouisnotwhite/Jetbrains-Fleet-Theme#6]
![735F289E-ED52-4D7D-9089-0321792250D1](https://user-images.githubusercontent.com/25947429/184374413-5be58850-d376-4e4a-af0a-43b30bec857d.jpeg)
如图，jetbrains新的new dark主题

**Comment by Michaelzhouisnotwhite** [comment]
等有具体的测试视频的时候，我找时间再做

**Comment by Michaelzhouisnotwhite** [comment]
Jetbrans New Dark Theme now is available on <https://marketplace.visualstudio.com/items?itemName=MichaelZhou.jetbrains-new-dark-theme>
