### ISSUE TITLE
html tags are the same color as text (React/JSX)

### ISSUE THREAD

**Issue by evertjr** [Michaelzhouisnotwhite/Jetbrains-Fleet-Theme#8]
<img width="267" alt="image" src="https://user-images.githubusercontent.com/13040196/192356802-13a1d7ec-0873-4381-8f55-0649250a5f2f.png">

Thanks for the theme, the color palette is great, but as mentioned in the title it makes reading jsx files kinda jarring, could you change the text inside the tags to white? I think it should be white based on the Fleet screenshots.

**Comment by Michaelzhouisnotwhite** [comment]
Can you give me a paragraph of sameple code? I don't write jsx.😉
