### ISSUE TITLE
跟fleet Dark主题有点差异

### ISSUE THREAD

**Issue by wavyhair** [Michaelzhouisnotwhite/Jetbrains-Fleet-Theme#9]
![diff](https://user-images.githubusercontent.com/87117512/195517605-1f093061-506c-4d64-aeac-7641e81466b9.jpg)
左上是vscode 右下是fleet Dark主题，标签的颜色不同呢。

**Comment by Michaelzhouisnotwhite** [comment]
I will fix the theme color in the next version.
